apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tc5-nfs-rwx-deploy-4gi
spec:
  replicas: 3
  selector:
    matchLabels:
      desire3d.io/name: tc5-nfs-rwx-pod
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        desire3d.io/name: tc5-nfs-rwx-pod
        desire3d.io/version: "1.0.0"
        desire3d.io/release: stable
        desire3d.io/tier: be
        desire3d.io/zone: prod
        desire3d.io/managed-by: m2
    spec:
      volumes:
        - name: nfs-tc5-rwx-4gi
          persistentVolumeClaim:
           # Local Storage Claim
           claimName: pvc-nfs-rwx-4gb-disk
      containers:
        - name: omega-dyn-ctr
          image: metamagic/oshell
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
          # Mount omega-volume-local from 
          # persistentVolumeClaim
            - mountPath: "/home/data"
              name: nfs-tc5-rwx-4gi